name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mongodb
          coverage: none

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: echo "Connection test successful"

      - name: Deploy to Server
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /root/project/sierra/MadProject || {
              echo "Directory not found"
              exit 1
            }
            
            echo "Starting deployment..."
            git pull origin main
            
            echo "Installing dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs
            
            echo "Clearing caches..."
            php artisan optimize:clear
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            
            echo "Recreating caches..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            echo "Setting permissions..."
            chown -R www-data:www-data .
            find . -type f -exec chmod 644 {} \;
            find . -type d -exec chmod 755 {} \;
            chmod -R 777 storage bootstrap/cache
            
            echo "Restarting PHP-FPM..."
            systemctl restart php8.2-fpm
            
            echo "Deployment completed successfully"