name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /root/project/sierra/MadProject
            git pull origin main
            pkill -f "php artisan serve" || true
            sleep 2
            php artisan serve --host=0.0.0.0 --port=8000 > server.log 2>&1 &
            sleep 5
            if pgrep -f "php artisan serve" > /dev/null; then
              echo "Server started successfully"
              exit 0
            else
              echo "Server failed to start"
              exit 1
            fi