name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/project/sierra/MadProject
            git pull origin main
            
            # Install PHP dependencies
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            
            # Install Node.js dependencies and build assets
            npm install
            npm run build
            
            # Clear and rebuild Laravel cache
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Run migrations if needed
            php artisan migrate --force
            
            # Fix permissions
            chmod -R 775 storage bootstrap/cache
            
            echo "Deployment completed"