name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: project/sierra/MadProject
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mongodb
          coverage: none
        
      - name: Copy .env
        working-directory: ./project/sierra/MadProject
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        
      - name: Install Dependencies
        working-directory: ./project/sierra/MadProject
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
        
      - name: Generate key
        working-directory: ./project/sierra/MadProject
        run: php artisan key:generate
        
      - name: Directory Permissions
        working-directory: ./project/sierra/MadProject
        run: chmod -R 777 storage bootstrap/cache
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/project/sierra/MadProject
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs
            php artisan optimize:clear
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Set proper permissions
            chown -R www-data:www-data .
            find . -type f -exec chmod 644 {} \;
            find . -type d -exec chmod 755 {} \;
            chmod -R 777 storage bootstrap/cache