name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /root/project/sierra/MadProject
            git pull origin main
            
            # Kill any existing Laravel process
            pkill -f "php artisan serve" || true
            
            # Start Laravel server with verbose output
            nohup php artisan serve --host=0.0.0.0 --port=8000 -v > storage/logs/server.log 2>&1 &
