name: Deploy Laravel to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /root/project/sierra/MadProject
            git pull origin main
            
            # Install MongoDB extension
            sudo apt-get update
            sudo apt-get install -y php-mongodb
            
            # Install dependencies with Composer
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs
            
            # Cache configuration
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Install and build frontend assets
            npm install
            npm run build
            
            # Run migrations
            php artisan migrate --force
            
            # Restart PHP to load new MongoDB extension
            sudo systemctl restart php8.3-fpm || true
            
            # Clear application cache
            php artisan cache:clear