name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/project/sierra/MadProject
            git pull origin main
            pkill -f "php artisan serve" || true
            echo "cd /root/project/sierra/MadProject && php artisan serve --host=0.0.0.0 --port=8000" | at now