name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/project/sierra/MadProject
            git pull origin main
            
            # Create startup script if it doesn't exist
            cat > start-server.sh << 'EOF'
            #!/bin/bash
            cd /root/project/sierra/MadProject
            pkill -f "php artisan serve" || true
            nohup php artisan serve --host=0.0.0.0 --port=8000 